version: "3.9"
services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '32181:2181'
    environment:
      - 'TZ=Asia/Shanghai'
    volumes:
      - './.env/zookeeper/data/:/data/'
      - './.env/zookeeper/datalog/:/datalog/'
      - './.env/zookeeper/logs/:/logs/'
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    hostname: kafka
    ports:
      - '39092:9092'
    working_dir: /opt/kafka/bin
    env_file:
      - ./sbkd.env
    environment:
      - 'TZ=Asia/Shanghai'
      - 'KAFKA_BROKER_ID=0'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092'
      - 'KAFKA_LOG_RETENTION_HOURS=720'
      - 'KAFKA_HEAP_OPTS=-Xmx512M -Xms128M'
    volumes:
      - ./.env/kafka:/kafka
    depends_on:
      - zookeeper
  kafka-eagle:
    image: nickzurich/efak:2.1.0
    container_name: kafka-eagle
    hostname: kafka-eagle
    environment:
      EFAK_CLUSTER_ZK_LIST: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "39094:8048"