server:
  port: ${SBKD_SERVER_PORT:10340}

spring:
  application:
    name: spring-boot-kafka-demo
  kafka:
    bootstrap-servers: localhost:39092
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 5
    consumer:
      auto-offset-reset: earliest
      max-poll-records: 1000
      fetch-max-wait: 10s
      auto-commit-interval: 5s
      enable-auto-commit: true

logging:
  level:
    root: info
    cn:
      netbuffer: debug

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: @project.name@
    version: ${APP_VERSION:v1.0.0}
  image:
    type: docker
    version: @project.version@